;this file for FamiTone2 library generated by text2data tool

powerglove5b_music_data:
	byte 1
	word .instruments
	word .samples-3
	word .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,256,213

.instruments:
	byte $30 ;instrument $00
	word .env6,.env17,.env0
	byte $00
	byte $30 ;instrument $07
	word .env2,.env14,.env0
	byte $00
	byte $30 ;instrument $08
	word .env2,.env15,.env0
	byte $00
	byte $30 ;instrument $0e
	word .env3,.env0,.env21
	byte $00
	byte $30 ;instrument $13
	word .env1,.env16,.env0
	byte $00
	byte $30 ;instrument $15
	word .env7,.env18,.env0
	byte $00
	byte $30 ;instrument $18
	word .env9,.env17,.env0
	byte $00
	byte $30 ;instrument $19
	word .env11,.env19,.env0
	byte $00
	byte $30 ;instrument $1a
	word .env10,.env17,.env0
	byte $00
	byte $30 ;instrument $1b
	word .env8,.env0,.env0
	byte $00
	byte $b0 ;instrument $1f
	word .env12,.env0,.env0
	byte $00
	byte $30 ;instrument $22
	word .env13,.env20,.env0
	byte $00
	byte $b0 ;instrument $24
	word .env5,.env0,.env0
	byte $00
	byte $b0 ;instrument $25
	word .env4,.env0,.env0
	byte $00

.samples:
.env0:
	byte $c0,$00,$00
.env1:
	byte $cb,$cb,$cc,$cc,$cd,$02,$ce,$02,$cf,$03,$ce,$03,$cd,$03,$cc,$cc
	byte $cb,$cb,$ca,$ca,$c9,$c8,$02,$c7,$05,$c6,$03,$c5,$04,$c4,$03,$c3
	byte $03,$c2,$04,$c1,$03,$c0,$00,$25
.env2:
	byte $cf,$06,$ce,$12,$cd,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c6,$c5
	byte $c5,$c4,$02,$c3,$c3,$c2,$00,$15
.env3:
	byte $cf,$cb,$c8,$c7,$c6,$c6,$c3,$00,$06
.env4:
	byte $c4,$03,$c2,$15,$c1,$09,$c1,$00,$06
.env5:
	byte $c8,$02,$c7,$03,$c6,$03,$c5,$c5,$c4,$02,$c3,$04,$c2,$04,$c1,$09
	byte $c1,$00,$10
.env6:
	byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0
	byte $00,$0f
.env7:
	byte $cf,$00,$00
.env8:
	byte $c0,$c4,$c5,$c5,$c7,$c9,$07,$c7,$05,$c6,$05,$c5,$04,$c4,$c4,$c3
	byte $00,$0f
.env9:
	byte $cb,$06,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$0a
.env10:
	byte $ca,$06,$c9,$0f,$c8,$03,$c7,$04,$c6,$02,$c5,$02,$c4,$03,$c3,$c3
	byte $c2,$00,$10
.env11:
	byte $c9,$c7,$04,$c4,$03,$c2,$03,$c1,$03,$c0,$00,$09
.env12:
	byte $cd,$ce,$06,$cd,$ce,$0e,$cd,$cc,$cc,$cb,$ca,$ca,$c9,$02,$c8,$c8
	byte $c7,$c7,$c6,$04,$c5,$06,$c4,$07,$c3,$05,$c2,$09,$c1,$c1,$c4,$11
	byte $c0,$c4,$09,$c3,$c0,$c3,$11,$c2,$02,$c0,$c0,$c2,$0a,$c1,$04,$c0
	byte $00,$2f
.env13:
	byte $c4,$c5,$c2,$c1,$c0,$00,$04
.env14:
	byte $c0,$c0,$c3,$c3,$c7,$c7,$cc,$cc,$00,$00
.env15:
	byte $c0,$c0,$c4,$c4,$c7,$c7,$cc,$cc,$00,$00
.env16:
	byte $cc,$cc,$c0,$c0,$00,$00
.env17:
	byte $d0,$cd,$c8,$c5,$c3,$c0,$00,$05
.env18:
	byte $cc,$c0,$00,$01
.env19:
	byte $c0,$c1,$c2,$00,$02
.env20:
	byte $be,$c0,$00,$01
.env21:
	byte $a0,$d5,$ff,$ff,$ff,$00,$03


.song0ch0:
	byte $fb,$06
.ref0:
	byte $94,$14,$8d,$00,$89,$0b,$14,$91,$00,$85,$0a,$81
.ref1:
	byte $10,$8d,$00,$89,$11,$0c,$93,$02,$1b,$18,$81
.ref2:
	byte $14,$85,$98,$3a,$44,$52,$5c,$9a,$3a,$44,$52,$5c,$83,$94,$0b,$14
	byte $85,$98,$3a,$44,$52,$5c,$9a,$3a,$44,$52,$5c,$83,$94,$0a,$81
.ref3:
	byte $10,$85,$98,$3a,$40,$52,$58,$9a,$3a,$40,$52,$58,$83,$94,$11,$0c
	byte $85,$98,$3c,$44,$54,$5c,$9a,$3c,$44,$54,$5c,$94,$1b,$18,$81
.ref4:
	byte $44,$85,$98,$3a,$44,$52,$5c,$9a,$3a,$44,$94,$3b,$45,$52,$89,$98
	byte $3a,$44,$52,$5c,$9a,$3a,$44,$94,$3b,$53,$4e,$81
.ref5:
	byte $58,$85,$98,$3a,$40,$52,$58,$94,$59,$52,$85,$52,$5e,$61,$62,$85
	byte $61,$58,$85,$52,$85
.ref6:
	byte $5c,$85,$98,$3a,$44,$52,$5c,$9a,$3a,$44,$94,$62,$60,$59,$53,$41
	byte $45,$98,$3a,$44,$52,$5c,$9a,$3a,$44,$52,$5c,$83,$94,$44,$81
.ref7:
	byte $40,$85,$98,$3a,$40,$52,$58,$94,$59,$52,$85,$52,$5e,$61,$63,$98
	byte $3c,$44,$94,$61,$58,$85,$52,$85
.song0ch0loop:
.ref8:
	byte $98,$44,$83,$9a,$44,$80,$14,$89,$94,$3b,$44,$9a,$3a,$94,$52,$9a
	byte $45,$52,$83,$80,$2c,$89,$94,$3b,$52,$9a,$3a,$94,$4e,$9a,$52
.ref9:
	byte $94,$58,$9a,$4f,$58,$80,$22,$85,$94,$59,$52,$9a,$59,$52,$94,$52
	byte $5e,$60,$9a,$52,$94,$62,$9a,$5e,$80,$0c,$9a,$62,$94,$61,$58,$9a
	byte $61,$58,$94,$52,$83,$9a,$52
.ref10:
	byte $94,$5c,$83,$98,$5c,$80,$15,$9a,$5c,$85,$94,$62,$60,$58,$98,$62
	byte $94,$52,$98,$58,$94,$40,$98,$52,$94,$44,$98,$40,$80,$2c,$98,$44
	byte $9a,$41,$44,$89,$94,$44,$81
.ref11:
	byte $40,$98,$45,$40,$80,$29,$9a,$41,$94,$59,$52,$98,$59,$52,$94,$52
	byte $5e,$60,$98,$52,$94,$62,$98,$60,$80,$0c,$98,$62,$94,$61,$58,$98
	byte $61,$58,$94,$53,$9a,$58,$98,$52
	byte $fd
	word .song0ch0loop

.song0ch1:
.ref12:
	byte $88,$14,$99,$0b,$14,$99,$0a,$81
.ref13:
	byte $10,$99,$11,$0c,$93,$02,$1b,$18,$81
.ref14:
	byte $14,$99,$0b,$14,$99,$0a,$81
	byte $ff,$09
	word .ref13
.ref16:
	byte $14,$8d,$92,$2c,$89,$88,$0b,$14,$8d,$92,$2c,$85,$31,$88,$0a,$81
.ref17:
	byte $10,$8d,$92,$28,$89,$88,$11,$0c,$85,$98,$3c,$44,$54,$5c,$92,$32
	byte $9a,$44,$54,$5c,$88,$1b,$18,$81
.ref18:
	byte $14,$8d,$92,$2c,$89,$88,$0b,$14,$8d,$92,$22,$85,$2d,$88,$0a,$81
.ref19:
	byte $10,$8d,$92,$36,$85,$3b,$88,$11,$0c,$8d,$8c,$24,$24,$25,$1b,$18
	byte $81
.song0ch1loop:
.ref20:
	byte $8e,$40,$83,$40,$82,$2d,$00,$2c,$83,$01,$8e,$41,$3d,$40,$83,$40
	byte $82,$2d,$00,$2d,$00,$83,$8e,$47,$40,$81
.ref21:
	byte $3c,$83,$3c,$84,$29,$00,$29,$00,$83,$8e,$39,$3d,$38,$83,$38,$84
	byte $25,$00,$24,$83,$01,$8e,$39,$36,$81
.ref22:
	byte $40,$83,$40,$82,$2d,$00,$2c,$83,$01,$8e,$41,$3d,$40,$83,$40,$82
	byte $2d,$00,$2d,$00,$83,$8e,$47,$40,$81
	byte $ff,$15
	word .ref21
	byte $fd
	word .song0ch1loop

.song0ch2:
.ref24:
	byte $8c,$2c,$99,$23,$2c,$99,$22,$81
.ref25:
	byte $28,$99,$29,$24,$93,$32,$1b,$30,$81
.ref26:
	byte $2c,$99,$23,$2c,$99,$22,$81
	byte $ff,$09
	word .ref25
	byte $ff,$07
	word .ref26
	byte $ff,$09
	word .ref25
.ref30:
	byte $14,$99,$23,$2c,$99,$22,$81
.ref31:
	byte $28,$99,$29,$24,$8d,$80,$44,$44,$45,$33,$2c,$81
.song0ch2loop:
.ref32:
	byte $8c,$2c,$85,$8a,$2c,$85,$8c,$15,$8a,$28,$2c,$83,$8c,$23,$2c,$85
	byte $8a,$2c,$85,$8c,$15,$8a,$1e,$22,$83,$8c,$22,$81
.ref33:
	byte $28,$85,$8a,$22,$85,$8c,$11,$8a,$29,$01,$8c,$29,$24,$85,$8a,$24
	byte $85,$8c,$0c,$83,$32,$1b,$18,$81
.ref34:
	byte $2c,$85,$8a,$2c,$85,$8c,$15,$8a,$28,$2c,$83,$8c,$23,$2c,$85,$8a
	byte $14,$85,$8c,$15,$8a,$1e,$22,$83,$8c,$22,$81
.ref35:
	byte $28,$85,$8a,$28,$85,$8c,$11,$8a,$29,$01,$8c,$29,$24,$85,$8a,$24
	byte $85,$80,$44,$44,$44,$8c,$32,$1b,$80,$3a,$81
	byte $fd
	word .song0ch2loop

.song0ch3:
.ref36:
	byte $8f,$90,$08,$95,$00,$95
.ref37:
	byte $8f,$06,$83,$08,$83,$20,$91,$00,$8d
.ref38:
	byte $8f,$08,$95,$00,$95
	byte $ff,$09
	word .ref37
.ref40:
	byte $8f,$06,$95,$00,$95
.ref41:
	byte $8f,$04,$83,$08,$83,$02,$91,$0c,$8d
.ref42:
	byte $87,$00,$85,$08,$8d,$00,$8d,$18,$16,$18,$10,$0c,$0a,$06,$02
.ref43:
	byte $87,$00,$85,$08,$83,$06,$83,$02,$91,$86,$08,$08,$09,$8c,$1f,$1a
	byte $18
.song0ch3loop:
.ref44:
	byte $92,$19,$96,$09,$80,$09,$96,$08,$08,$83,$09,$80,$09,$96,$08,$08
	byte $83,$09,$80,$09,$96,$08,$08,$83,$09,$80,$09,$96,$08,$08
.ref45:
	byte $83,$09,$80,$09,$96,$08,$08,$83,$09,$80,$09,$96,$08,$08,$83,$09
	byte $80,$09,$96,$08,$08,$83,$09,$80,$09,$96,$08,$08
	byte $ff,$14
	word .ref44
	byte $ff,$14
	word .ref45
	byte $fd
	word .song0ch3loop

.song0ch4:
.ref48:
	byte $bf
.ref49:
	byte $bf
.ref50:
	byte $bf
.ref51:
	byte $bf
.ref52:
	byte $bf
.ref53:
	byte $bf
.ref54:
	byte $bf
.ref55:
	byte $bf
.song0ch4loop:
.ref56:
	byte $bf
.ref57:
	byte $bf
.ref58:
	byte $bf
.ref59:
	byte $bf
	byte $fd
	word .song0ch4loop
